### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by PrashanthKumarM** [p632-sp-2017/action-list#22]
Create new filters for the action list.

**Comment by stephenpaul2727** [comment]
I see that filters can be grouped into the following : 
1. Document Route Status ----
2. Action Requested ----
3. Dates Created Range --- From [] to TO []
4. Dates Last Assigned --- From [] to TO []
5. Document Type 

There are more filters in the web action list. But I guess the above mentioned should suffice the purpose. 
There is filter by document name which we will incorporate in search bar on our App.
Any Comments on this Comment?

**Comment by burnumd** [comment]
Document Type is another one people will want to filter on.

**Comment by stephenpaul2727** [comment]
Can you provide some examples of the document types available?
Thanks

**Comment by stephenpaul2727** [comment]
![screen shot 2017-03-17 at 3 02 10 pm](https://cloud.githubusercontent.com/assets/21348747/24058756/c858c648-0b22-11e7-965f-3b77a6b9b351.png)

**Comment by burnumd** [comment]
It should probably check against all the document types in the user's action list and populate the document type filter with those document type names (the web view gives a count of how many docs of those type are in the user's action list).

**Comment by stephenpaul2727** [comment]
Understood, For example a TK Timesheet is one type of document. I don't have a good idea of what type of other documents are there. I'm thinking we should give him a list of such types of documents out of which he will choose a filter right? 

do we require the count of a certain document?

**Comment by PrashanthKumarM** [comment]
#66
