### ISSUE TITLE
RIght Draw Design

### ISSUE THREAD

**Issue by PrashanthKumarM** [p632-sp-2017/action-list#23]
Build new styling and appropriate elements for the right draw.

**Comment by ShalakaSharma** [comment]
![drawer - document type](https://cloud.githubusercontent.com/assets/10527470/24381120/9164de2c-131c-11e7-833a-8f5986b2354c.jpg)
![drawer - expanded action requested](https://cloud.githubusercontent.com/assets/10527470/24381122/91683a0e-131c-11e7-822a-632da5602566.jpeg)
![drawer - expanded document route status](https://cloud.githubusercontent.com/assets/10527470/24381117/916387fc-131c-11e7-8ef0-e8a0b14bc0f0.jpg)
![drawer 1](https://cloud.githubusercontent.com/assets/10527470/24381119/9164844a-131c-11e7-9d51-4b7c02c78123.jpg)
![drawer - document assigned](https://cloud.githubusercontent.com/assets/10527470/24381118/916498cc-131c-11e7-969d-12881d716983.jpg)
![drawer - document create](https://cloud.githubusercontent.com/assets/10527470/24381121/91655866-131c-11e7-8979-4a2e4a5c05e3.jpg)

**Comment by ShalakaSharma** [comment]
![drawer - sorting](https://cloud.githubusercontent.com/assets/10527470/24884524/c7987372-1e17-11e7-855a-356169c6a6e7.jpg)

All designs created and approved.
