### ISSUE TITLE
Create Designs

### ISSUE THREAD

**Issue by PrashanthKumarM** [p632-sp-2017/action-list#5]
Create designs with the branding guidelines and elements to be displayed from the wireframes.

**Comment by ShalakaSharma** [comment]
Designs for displaying action list with open and closed cards were made and approved.

![design](https://cloud.githubusercontent.com/assets/10527470/23384440/f8bc6e1a-fd18-11e6-8a57-325dc34c4984.jpg)
![design expanded card](https://cloud.githubusercontent.com/assets/10527470/23384441/f8bcdee0-fd18-11e6-90db-3ba7098040bf.jpg)

**Comment by ShalakaSharma** [comment]
Closing this issue
